export * from './Banner/Banner'
export * from './OfferBanner/OfferBanner'
export * from './Categories/Categories'
export * from './Testimonials/Testimonials'
export * from './Offer/Offer'
export * from './WhoWeAre/WhoWeAre'
export * from './Gallery/Gallery'
export * from './News/News'
